---

- name: Login to registry if private registry is configured
  containers.podman.podman_login:
    registry: "{{ rhads_rhel_execution_environment_registry_url }}"
    username: "{{ rhads_rhel_execution_environment_registry_username }}"
    password: "{{ rhads_rhel_execution_environment_registry_password }}"
  when:
    - rhads_rhel_execution_environment_registry_url is defined
    - rhads_rhel_execution_environment_registry_username is defined
    - rhads_rhel_execution_environment_registry_password is defined
  no_log: true

- name: Pull execution environment image from quay.io
  containers.podman.podman_image:
    name: "{{ rhads_rhel_execution_environment_image_name }}:{{ rhads_rhel_execution_environment_image_name_tag }}"
    pull: true
    state: present
  register: _r_pull_result

- name: Retag the downloaded ee image
  containers.podman.podman_image:
    name: "{{ rhads_rhel_execution_environment_image_name }}:{{ rhads_rhel_execution_environment_image_name_tag }}"
    tag: "{{ rhads_rhel_execution_environment_retag_image_name }}:{{ rhads_rhel_execution_environment_retag_image_tag }}"
    state: present
  when:
    - _r_pull_result is succeeded
    - rhads_rhel_execution_environment_retag_image | bool

- name: Remove the original downloaded execution environment after retag
  containers.podman.podman_image:
    name: "{{ rhads_rhel_execution_environment_image_name }}:{{ rhads_rhel_execution_environment_image_name_tag }}"
    state: absent
  when:
    - _r_pull_result is succeeded
    - rhads_rhel_execution_environment_retag_image | bool

- name: Display pull results
  debug:
    msg: "Successfully downloaded execution environment: {{ ee_image }}" 
  when: _r_pull_result is succeeded

