---
- name: Install python3-pip
  ansible.builtin.yum:
    name: python3-pip

- name: Install certbot
  ansible.builtin.pip:
    name: certbot

- name: Run certbot
  register: r_certbot
  until: r_certbot is success
  retries: 5
  delay: 60
  ansible.builtin.command: |
    /usr/local/bin/certbot certonly -n --agree-tos --email rhpds@redhat.com -d {{ certbot_domains | join (' -d ') }}
    --eab-kid "{{ certbot_cert_manager_zerossl_eab_key_id }}"
    --eab-hmac-key "{{ certbot_cert_manager_zerossl_hmac_key }}"
    --server "{{ certbot_cert_manager_acme_url }}" --standalone --preferred-challenges http
  loop: "{{ rhads_rhel_certbot_certificates }}"
  loop_control:
    loop_var: certbot_domains

- name: Fetch certificates
  ansible.builtin.fetch:
    src: /etc/letsencrypt/live/{{ certbot_domains.0.0 }}/{{ certbot_domains.1 }}
    dest: /tmp/{{ certbot_domains.0.0 }}{{ certbot_domains.1 }}
    flat: true
  loop: "{{ rhads_rhel_certbot_certificates | zip('fullchain.pem','privkey.pem') | list  }}"
  loop_control:
    loop_var: certbot_domains
