---
- name: Install python3-pip
  ansible.builtin.yum:
    name: python3-pip

- name: Install certbot
  ansible.builtin.pip:
    name: certbot

- name: Debug domains
  debug:
    msg: "{{ rhads_rhel_certbot_certificates }}"

- fail:
